Repository SheepCreativeSoftware/msfs2020-C208-Improvment-Mod, pull requests merged in 2022-03, with the labels that each got.

#119 Pull for release after testing
  C208B-mod/ContentInfo/Sheep_208B_GRAND_CARAVAN_EX_Impro/Thumbnail.jpg
  C208B-mod/Effects/LIGHT_C208_CabinBounce.fx
  C208B-mod/Effects/LIGHT_C208_CockpitSpot.fx
  C208B-mod/Effects/LIGHT_C208_CockpitSpotLarge.fx
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/Climb.flt
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/approach.FLT
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/apron.flt
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/cruise.FLT
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/engines.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/final.FLT
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/flight_model.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/hangar.flt
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR_LOD00.gltf
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR_LOD04.gltf
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_propeller.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_templates.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/runway.FLT
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/sound/sound.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/systems.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/taxi.flt
  C208B-mod/layout.json
  C208B-mod/manifest.json
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_ALBD.PNG.DDS
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_ALBD.PNG.DDS.json
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_COMP.PNG.DDS
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_COMP.PNG.DDS.json
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_NORM.PNG.DDS
  C208B-mod/texture/GAUGES/AIRSPEEDINDICATOR_CARAVAN_NORM.PNG.DDS.json
  C208B-mod/texture/GAUGES/AirspeedIndicator_CARAVAN_norm.png
  C208B-mod/texture/GAUGES/AirspeedIndicator_Caravan_albd.png
  C208B-mod/texture/GAUGES/AirspeedIndicator_Caravan_comp.png
  CHANGELOG.md
  README.md
Labels: release

#128 fix: Autostart procedure was incomple / Autostop did no work at all
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_templates.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  README.md
Labels: bug, enhancement

#143 v2203.2.2
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_propeller.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_templates.xml
  C208B-mod/de-DE.locPak
  C208B-mod/en-US.locPak
  C208B-mod/es-ES.locPak
  C208B-mod/fi-FI.locPak
  C208B-mod/fr-FR.locPak
  C208B-mod/it-IT.locPak
  C208B-mod/ja-JP.locPak
  C208B-mod/layout.json
  C208B-mod/manifest.json
  C208B-mod/nb-NO.locPak
  C208B-mod/nl-NL.locPak
  C208B-mod/pl-PL.locPak
  C208B-mod/pt-BR.locPak
  C208B-mod/ru-RU.locPak
  C208B-mod/sv-SE.locPak
  CHANGELOG.md
  README.md
Labels: bug, enhancement, release
