Repository SheepCreativeSoftware/msfs2020-C208-Improvment-Mod, pull requests merged in 2022-01, with the labels that each got.

#92 Metal chip detection
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  README.md
Labels: enhancement, test

#99 a couple of small various fixes left after last pull.
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/engines.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/flight_model.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR_LOD00.gltf
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  README.md
Labels: enhancement

#103 Battery current indications
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
Labels: enhancement

#105 Release Beta
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/flight_model.cfg
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  C208B-mod/layout.json
  C208B-mod/manifest.json
  CHANGELOG.md
Labels: release

#106 Fixed: Fuel consumption is not zero when engine isn't started
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  C208B-mod/layout.json
Labels: release

#107 stby torque is scaled up to 3000 foot pounds now
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/TEXTURE/CESSNA_208B_GRANDCARAVANEX_COCKPIT_DECALS_GAUGES_ALBD.PNG.dds
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
Labels: enhancement

#108 Beta
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/TEXTURE/CESSNA_208B_GRANDCARAVANEX_COCKPIT_DECALS_GAUGES_ALBD.PNG.dds
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  CHANGELOG.md
Labels: enhancement

#111 fix: Master battery set button does not work on honeycomb volant
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
Labels: bug

#112 Fix misc
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/sound/sound.xml
Labels: bug, enhancement

#114 Beta
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/model/208B_GRAND_CARAVAN_EX_INTERIOR.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/panel/Panel.xml
  C208B-mod/SimObjects/Airplanes/Asobo_208B_GRAND_CARAVAN_EX/sound/sound.xml
  C208B-mod/layout.json
  C208B-mod/manifest.json
  CHANGELOG.md
Labels: release
